# Week 3: Data Collection, Cleaning, and Manipulation with Pandas

`Pandas` offers several built-in functionalities for **directly handling datasets**, for example for the CSV format. We will see how to leverage the knowledge that you just acquired for data analysis purposes. <br>
<br>
As usual, we start by importing `pandas`.

In [1]:
import pandas as pd

To test `pandas` for data analysis, we will use a dataset freely available on Kaggle. The following cell downloads the dataset and prints out **its path on your laptop**. <br> <br>
You might need to install some of the libraries imported in this notebook. To do so, you can run a cell of the notebook as follows:

In [2]:
!pip install kagglehub # the ! allows you to run the pip install (a terminal command) directly in the notebook

Requirement already satisfied: kagglehub in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (0.4.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (from kagglehub) (0.1.15)
Requirement already satisfied: packaging in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (from requests->kagglehub) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (from requests->kagglehub) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (from requests->kagglehub) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /home/cgraiff/miniconda3/envs/transf_env/lib/python3.12/site-packages (from requests->kagglehub) (2025.1.31)

In [3]:
# Import necessary libraries

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("imdevskp/corona-virus-report")
#path = kagglehub.dataset_download("ignacioazua/world-gdp-population-and-co2-emissions-dataset")

print("Path to dataset files:", path)

print("Path to dataset files:", path) # Path to the downloaded folder 
filename = os.listdir(path)
print(filename) # Shows content of the folder
filepath=os.path.join(path, "covid_19_clean_complete.csv")
print(filepath)

Path to dataset files: /home/cgraiff/.cache/kagglehub/datasets/imdevskp/corona-virus-report/versions/166
Path to dataset files: /home/cgraiff/.cache/kagglehub/datasets/imdevskp/corona-virus-report/versions/166
['country_wise_latest.csv', 'worldometer_data.csv', 'day_wise.csv', 'covid_19_clean_complete.csv', 'usa_county_wise.csv', 'full_grouped.csv']
/home/cgraiff/.cache/kagglehub/datasets/imdevskp/corona-virus-report/versions/166/covid_19_clean_complete.csv

#### 1. Data Collection
Read CSV and access its content.

We can now use the above link to open the dataset **directly as a `pandas` dataframe object**. To do so, we can use the `read_csv` method.
> `NaN` defines **empty values**.

In [29]:
# Open dataset as pandas dataframe
df = pd.read_csv('/home/cgraiff/.cache/kagglehub/datasets/imdevskp/corona-virus-report/versions/166/covid_19_clean_complete.csv') #change with your path (printed above)
# Visualize the first 5 rows of dataframe
df.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa

In [77]:
# Visualize the last 5 rows of dataframe
df.tail()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

#### Accessing values in the dataframe
Accessing a column is quite straightforward:

In [46]:
# To access a column in the DataFrame.
countries = df['Country/Region']
print(countries)

0                  Afghanistan
1                      Albania
2                      Algeria
3                      Andorra
4                       Angola
                 ...
49063    Sao Tome and Principe
49064                    Yemen
49065                  Comoros
49066               Tajikistan
49067                  Lesotho
Name: Country/Region, Length: 49068, dtype: object

In [ ]:
# Exercise: display the 'deaths' column. Use only one line of code.

In [ ]:
# Solution
print(df['Deaths'])

In [79]:
# Access multiple columns
df[['Country/Region', 'Recovered']] # Careful of the double brackets!

              Country/Region  Recovered
0                Afghanistan          0
1                    Albania          0
2                    Algeria          0
3                    Andorra          0
4                     Angola          0
...                      ...        ...
49063  Sao Tome and Principe        734
49064                  Yemen        833
49065                Comoros        328
49066             Tajikistan       6028
49067                Lesotho        128

[49068 rows x 2 columns]

The `iloc` and `loc` operators are useful to select rows. `iloc` selects rows by index, and `loc` selects them by label.

In [80]:
# Selecting row by index
# First row
df.iloc[0]

Province/State                      NaN
Country/Region              Afghanistan
Lat                            33.93911
Long                          67.709953
Date                         2020-01-22
Confirmed                             0
Deaths                                0
Recovered                             0
Active                                0
WHO Region        Eastern Mediterranean
Name: 0, dtype: object

In [ ]:
# Exercise: Select the first 5 rows
# Hint: Think of what we learnt about slicing last week!

In [ ]:
# Solution: First 5 rows
df.iloc[0:5]

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa

In [ ]:
# Exercise: select the last row

In [ ]:
# Solution
# Last row
df.iloc[-1]

Province/State           NaN
Country/Region       Lesotho
Lat                   -29.61
Long                 28.2336
Date              2020-07-27
Confirmed                505
Deaths                    12
Recovered                128
Active                   365
WHO Region            Africa
Name: 49067, dtype: object

In [83]:
# Selecting rows by label
df.loc[2]

Province/State           NaN
Country/Region       Algeria
Lat                  28.0339
Long                  1.6596
Date              2020-01-22
Confirmed                  0
Deaths                     0
Recovered                  0
Active                     0
WHO Region            Africa
Name: 2, dtype: object

> Remember: Indexing in Python always starts by 0, so selecting index 1 is different from selecting label 1. Index 1 will be the second row, label 1 will be the first row.

To select both rows and columns, you can combine the above mentioned methods.

In [ ]:
# Exercise: Select rows 0 to 2 AND columns 1 to 2 using iloc
# Hint: With iloc, you specify first rows, then columns.

In [ ]:
# Solution
# Using iloc: row 0-2, columns 1-2
df.iloc[0:3, 1:3]

  Country/Region       Lat
0    Afghanistan  33.93911
1        Albania  41.15330
2        Algeria  28.03390

In [ ]:
# Exercise: Select rows 0 to 2 AND columns 'Country/Region' and 'Deaths' using iloc
# Hint: With loc, you specify first row numbers, then column names.

In [ ]:
# Solution
# Using loc: rows 0-2, specific columns
df.loc[0:2, ['Country/Region', 'Deaths']]

  Country/Region  Deaths
0    Afghanistan       0
1        Albania       0
2        Algeria       0

You can also select rows that contain a specific value.

In [86]:
# Rows where country is either France or Germany
df[df['Country/Region'].isin(['France', 'Germany'])]

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
105,French Guiana,France,3.933900,-53.125800,2020-01-22,0,0,0,0,Europe
106,French Polynesia,France,-17.679700,149.406800,2020-01-22,0,0,0,0,Europe
107,Guadeloupe,France,16.265000,-61.551000,2020-01-22,0,0,0,0,Europe
108,Mayotte,France,-12.827500,45.166244,2020-01-22,0,0,0,0,Europe
109,New Caledonia,France,-20.904305,165.618042,2020-01-22,0,0,0,0,Europe
...,...,...,...,...,...,...,...,...,...,...
48919,St Martin,France,18.070800,-63.050100,2020-07-27,49,3,41,5,Europe
48920,Martinique,France,14.641500,-61.024200,2020-07-27,269,15,98,156,Europe
48921,NaN,France,46.227600,2.213700,2020-07-27,208665,30096,71497,107072,Europe
48925,NaN,Germany,51.165691,10.451526,2020-07-27,207112,9125,190314,7673,Europe
49060,Saint Pierre and Miquelon,France,46.885200,-56.315900,2020-07-27,4,0,1,3,Europe

In [ ]:
# Exercise: select rows where the deaths are at least 5000

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
15795,NaN,Italy,41.871940,12.567380,2020-03-22,59138,5476,7024,46638,Europe
16056,NaN,Italy,41.871940,12.567380,2020-03-23,63927,6077,7024,50826,Europe
16317,NaN,Italy,41.871940,12.567380,2020-03-24,69176,6820,8326,54030,Europe
16578,NaN,Italy,41.871940,12.567380,2020-03-25,74386,7503,9362,57521,Europe
16839,NaN,Italy,41.871940,12.567380,2020-03-26,80589,8215,10361,62013,Europe
...,...,...,...,...,...,...,...,...,...,...
49006,NaN,Spain,40.463667,-3.749220,2020-07-27,272421,28432,150376,93613,Europe
49010,NaN,Sweden,60.128161,18.643501,2020-07-27,79395,5700,0,73695,Europe
49018,NaN,Turkey,38.963700,35.243300,2020-07-27,227019,5630,210469,10920,Europe
49028,NaN,United Kingdom,55.378100,-3.436000,2020-07-27,300111,45759,0,254352,Europe
49030,NaN,US,40.000000,-100.000000,2020-07-27,4290259,148011,1325804,2816444,Americas

In [ ]:
# Solution: rows where deaths are at least 5000
df[df['Deaths'] >= 5000]

#### Slicing rows

In [ ]:
# Select the first two rows. Remember what we learnt last week about slicing lists, and apply it here.

In [ ]:
# Solution: slicing rows
subset = df[0:2]  # First two rows
print(subset)

  Province/State Country/Region       Lat       Long        Date  Confirmed  \
0            NaN    Afghanistan  33.93911  67.709953  2020-01-22          0
1            NaN        Albania  41.15330  20.168300  2020-01-22          0

   Deaths  Recovered  Active             WHO Region
0       0          0       0  Eastern Mediterranean
1       0          0       0                 Europe

##### Accessing string values
If the value you access is a *string*, you can perform on it the basic string operations discussed last week.

In [88]:
access_str_df=df['Country/Region'][0:5].str.replace("Afghanistan", "afg")
access_str_df.head()

0        afg
1    Albania
2    Algeria
3    Andorra
4     Angola
Name: Country/Region, dtype: object

Of course, this is just an example, and other string operations work too. For example, you can leverage this property for filtering. Try doing the following exercises:

In [ ]:
# Exercise: select rows where country starts with 'F'

# Exercise: select rows where country name contains 'Fra'

In [ ]:
# Solution
#  Rows where country starts with 'F'
df[df['Country/Region'].str.startswith('F')]

# Rows where country name contains 'Fra'
df[df['Country/Region'].str.contains('Fra')]

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
105,French Guiana,France,3.933900,-53.125800,2020-01-22,0,0,0,0,Europe
106,French Polynesia,France,-17.679700,149.406800,2020-01-22,0,0,0,0,Europe
107,Guadeloupe,France,16.265000,-61.551000,2020-01-22,0,0,0,0,Europe
108,Mayotte,France,-12.827500,45.166244,2020-01-22,0,0,0,0,Europe
109,New Caledonia,France,-20.904305,165.618042,2020-01-22,0,0,0,0,Europe
...,...,...,...,...,...,...,...,...,...,...
48918,Saint Barthelemy,France,17.900000,-62.833300,2020-07-27,7,0,6,1,Europe
48919,St Martin,France,18.070800,-63.050100,2020-07-27,49,3,41,5,Europe
48920,Martinique,France,14.641500,-61.024200,2020-07-27,269,15,98,156,Europe
48921,NaN,France,46.227600,2.213700,2020-07-27,208665,30096,71497,107072,Europe
49060,Saint Pierre and Miquelon,France,46.885200,-56.315900,2020-07-27,4,0,1,3,Europe

#### 2. Data Cleaning
We saw that the dataset has some missing values. Let's handle them.
The method `isnull` prints `True` if the value is missing, `False` otherwise.

In [90]:
df["Province/State"].isnull()

0        True
1        True
2        True
3        True
4        True
         ...
49063    True
49064    True
49065    True
49066    True
49067    True
Name: Province/State, Length: 49068, dtype: bool

We see that the column `Province/State` contains several missing values. We can print out the amount of missing values with `value_counts()`:

In [91]:
df["Province/State"].isnull().value_counts()

Province/State
True     34404
False    14664
Name: count, dtype: int64

`dropna` removes the rows with missing values. Let's do it for the `Province/State` column.

In [92]:
df_clean_province_values = df["Province/State"].dropna()
df_clean_province_values.head()

8     Australian Capital Territory
9                  New South Wales
10              Northern Territory
11                      Queensland
12                 South Australia
Name: Province/State, dtype: object

Good, but we need to see the whole df. Let's apply the same method to the `Province/State` column, but for the whole dataset.

In [93]:
df_clean_province_values = df.dropna(subset=['Province/State'])
df_clean_province_values.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
8,Australian Capital Territory,Australia,-35.4735,149.0124,2020-01-22,0,0,0,0,Western Pacific
9,New South Wales,Australia,-33.8688,151.2093,2020-01-22,0,0,0,0,Western Pacific
10,Northern Territory,Australia,-12.4634,130.8456,2020-01-22,0,0,0,0,Western Pacific
11,Queensland,Australia,-27.4698,153.0251,2020-01-22,0,0,0,0,Western Pacific
12,South Australia,Australia,-34.9285,138.6007,2020-01-22,0,0,0,0,Western Pacific

An alternative could be filling the missing values with 0.

In [94]:
df_zeros=df.fillna(0)  # Replace missing values with 0
df_zeros.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,0,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,0,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,0,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,0,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,0,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa

In [95]:
# If you want to modify the dataframe directly, run:
#df.fillna(0, inplace=True)

In case of **numerical values**, replacing the item with **the mean** is also very useful: `df.fillna(df.mean())`

Part of data cleaning is also **choosing the right strategy**. For example, another method is **filling with forward propagation**: the value previous to the null value in the column will be used to fill the null value. Similarly, **backward propagation** will mean that the value after the null value is used to fill the null value. In our case, `ffill` cannot be applied, as the first row already contains a NaN value.

In [96]:
df_backward=df.bfill()
df_backward.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,Australian Capital Territory,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,Australian Capital Territory,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,Australian Capital Territory,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,Australian Capital Territory,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,Australian Capital Territory,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa

Clearly, this method is **not useful in this context**, as it would return values that are simply wrong. You can find more information about techniques to handle missing values in the dedicated dataset. However, choosing the technique will mostly depend on your own data and research question, as more elaborate statistical methods are not into the scope of this class. You will be asked to choose based on the properties of your data: For example, replacing NaNs with 0 in continuous variables (like height, temperature, income) can artificially lower the mean and inflate variance, which would be bad.

##### Duplicate values
Below, you can see the code to **check for duplicate values**.

In [ ]:
df.duplicated().any()

np.False_

As you can see, this specific dataset contains no duplicates. For the purpose of this class, let's **add some duplicate values** and then remove them (for learning purposes!).

In [ ]:
# Create 5 random duplicate rows
duplicates = df.sample(5, random_state=42)
print(duplicates)

      Province/State Country/Region        Lat        Long        Date  \
2984      Martinique         France  14.641500  -61.024200  2020-02-02
32749            NaN          Haiti  18.971200  -72.285200  2020-05-26
33124            NaN  Guinea-Bissau  11.803700  -15.180400  2020-05-27
23158            NaN   Saudi Arabia  23.885942   45.079162  2020-04-19
29025        Guangxi          China  23.829800  108.788100  2020-05-12

       Confirmed  Deaths  Recovered  Active             WHO Region
2984           0       0          0       0                 Europe
32749       1174      33         22    1119               Americas
33124       1195       7         42    1146                 Africa
23158       9362      97       1398    7867  Eastern Mediterranean
29025        254       2        252       0        Western Pacific

In [ ]:
# Append duplicates to the original df
df_with_duplicates = pd.concat([df, duplicates], ignore_index=True) # We add ignore_index to prevent confusion with repeated indexes. It is a "safety measure"

df_with_duplicates.shape

(49073, 10)

In [ ]:
# Exercise: Check for duplicates

In [ ]:
# Solution: Check for duplicates
df_with_duplicates.duplicated().any()

np.True_

In [ ]:
# Display duplicates
df_with_duplicates[df_with_duplicates.duplicated()]

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
49068,Martinique,France,14.641500,-61.024200,2020-02-02,0,0,0,0,Europe
49069,NaN,Haiti,18.971200,-72.285200,2020-05-26,1174,33,22,1119,Americas
49070,NaN,Guinea-Bissau,11.803700,-15.180400,2020-05-27,1195,7,42,1146,Africa
49071,NaN,Saudi Arabia,23.885942,45.079162,2020-04-19,9362,97,1398,7867,Eastern Mediterranean
49072,Guangxi,China,23.829800,108.788100,2020-05-12,254,2,252,0,Western Pacific

In [14]:
# Remove duplicates
df_clean = df_with_duplicates.drop_duplicates()

In [ ]:
# Check dataset
df_clean.duplicated().any()
# Eventually, you can also use the following:
# df_clean.duplicated().sum()

np.False_

##### Standardizing categories
Below, you can check the unique values of a specific column. In this case, the dataset does not present inconsistent values.

In [19]:
df['WHO Region'].unique()

array(['Eastern Mediterranean', 'Europe', 'Africa', 'Americas',
       'Western Pacific', 'South-East Asia'], dtype=object)

Let's create a dataset with inconsistent values as an exercise, and clean it:

In [21]:
data = {
    'Country/Region': ['France', 'Italy', 'Guinea_Bissau', 'Saudi Arabia', 'China'],
    'WHO Region': ['Europe', 'EU', 'Africa', 'Eastern Mediterranean', 'Western Pacific'],
}

non_standard_df = pd.DataFrame(data)
non_standard_df

  Country/Region             WHO Region
0         France                 Europe
1          Italy                     EU
2  Guinea_Bissau                 Africa
3   Saudi Arabia  Eastern Mediterranean
4          China        Western Pacific

In [ ]:
# Exercise: Check unique values in the above created dataframe

In [ ]:
# Solution
non_standard_df["WHO Region"].unique()

array(['Europe', 'EU', 'Africa', 'Eastern Mediterranean',
       'Western Pacific'], dtype=object)

In [ ]:
# Exercise: Try replacing them.
# Hint: You can apply the method 'replace()' to the 'WHO Region' column. Inside 'replace()', 
# you need to insert a dictionary where the keys are the values to be changed, 
# and the values are the actual values you want to see in the df.

In [ ]:
# Solution: Replacing unique values

non_standard_df['WHO Region'] = non_standard_df['WHO Region'].replace({
    'EU': 'Europe'
})
non_standard_df

  Country/Region             WHO Region
0         France                 Europe
1          Italy                 Europe
2  Guinea_Bissau                 Africa
3   Saudi Arabia  Eastern Mediterranean
4          China        Western Pacific

#### 3. Filtering
You can **select rows** based on specific conditions.

In [ ]:
# Select rows where the country is France

filtered_France = df[df['Country/Region']=="France"]
filtered_France.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
105,French Guiana,France,3.933900,-53.125800,2020-01-22,0,0,0,0,Europe
106,French Polynesia,France,-17.679700,149.406800,2020-01-22,0,0,0,0,Europe
107,Guadeloupe,France,16.265000,-61.551000,2020-01-22,0,0,0,0,Europe
108,Mayotte,France,-12.827500,45.166244,2020-01-22,0,0,0,0,Europe
109,New Caledonia,France,-20.904305,165.618042,2020-01-22,0,0,0,0,Europe

In [ ]:
# Exercise: select rows where the recovered are more than 1000.

In [ ]:
# Solution

filtered_df = df[df['Recovered'] > 1000]  # Rows where recovered are more than 1000
print(filtered_df)

      Province/State Country/Region        Lat        Long        Date  \
4237           Hubei          China  30.975600  112.270700  2020-02-07
4498           Hubei          China  30.975600  112.270700  2020-02-08
4759           Hubei          China  30.975600  112.270700  2020-02-09
5020           Hubei          China  30.975600  112.270700  2020-02-10
5281           Hubei          China  30.975600  112.270700  2020-02-11
...              ...            ...        ...         ...         ...
49050            NaN         Kosovo  42.602636   20.902977  2020-07-27
49057            NaN   Sierra Leone   8.460555  -11.779889  2020-07-27
49058            NaN         Malawi -13.254300   34.301500  2020-07-27
49061            NaN    South Sudan   6.877000   31.307000  2020-07-27
49066            NaN     Tajikistan  38.861000   71.276100  2020-07-27

       Confirmed  Deaths  Recovered  Active       WHO Region
4237       24953     699       1115   23139  Western Pacific
4498       27100     780       1439   24881  Western Pacific
4759       29631     871       1795   26965  Western Pacific
5020       31728     974       2222   28532  Western Pacific
5281       33366    1068       2639   29659  Western Pacific
...          ...     ...        ...     ...              ...
49050       7413     185       4027    3201           Europe
49057       1783      66       1317     400           Africa
49058       3664      99       1645    1920           Africa
49061       2305      46       1175    1084           Africa
49066       7235      60       6028    1147           Europe

[10159 rows x 10 columns]

#### Sort data

In [ ]:
# Sort data in descending order
df.sort_values(by='Deaths', ascending=False) # or ascending=True for ascending order

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
49030,NaN,US,40.0000,-100.0000,2020-07-27,4290259,148011,1325804,2816444,Americas
48769,NaN,US,40.0000,-100.0000,2020-07-26,4233923,146935,1297863,2789125,Americas
48508,NaN,US,40.0000,-100.0000,2020-07-25,4178970,146465,1279414,2753091,Americas
48247,NaN,US,40.0000,-100.0000,2020-07-24,4112531,145560,1261624,2705347,Americas
47986,NaN,US,40.0000,-100.0000,2020-07-23,4038816,144430,1233269,2661117,Americas
...,...,...,...,...,...,...,...,...,...,...
32,NaN,Cabo Verde,16.5388,-23.0418,2020-01-22,0,0,0,0,Africa
33,NaN,Cambodia,11.5500,104.9167,2020-01-22,0,0,0,0,Western Pacific
34,NaN,Cameroon,3.8480,11.5021,2020-01-22,0,0,0,0,Africa
16,NaN,Austria,47.5162,14.5501,2020-01-22,0,0,0,0,Europe
15,Western Australia,Australia,-31.9505,115.8605,2020-01-22,0,0,0,0,Western Pacific

In [ ]:
# Exercise: Sort df by ascending order of confirmed cases values.

In [100]:
# Sorting by index
df.sort_index()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
...,...,...,...,...,...,...,...,...,...,...
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

##### Grouping and aggregating
`Pandas` offers useful ways of grouping data, e.g. by using the `groupby` operator. In the following example, you will see how to group the dataset by WHO region:

In [35]:
df_grouped = df.groupby('WHO Region')
df_grouped.get_group('Europe')

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
1,NaN,Albania,41.1533,20.1683,2020-01-22,0,0,0,0,Europe
3,NaN,Andorra,42.5063,1.5218,2020-01-22,0,0,0,0,Europe
7,NaN,Armenia,40.0691,45.0382,2020-01-22,0,0,0,0,Europe
16,NaN,Austria,47.5162,14.5501,2020-01-22,0,0,0,0,Europe
17,NaN,Azerbaijan,40.1431,47.5769,2020-01-22,0,0,0,0,Europe
...,...,...,...,...,...,...,...,...,...,...
49053,British Virgin Islands,United Kingdom,18.4207,-64.6400,2020-07-27,8,1,7,0,Europe
49054,Turks and Caicos Islands,United Kingdom,21.6940,-71.7979,2020-07-27,99,2,36,61,Europe
49059,Falkland Islands (Malvinas),United Kingdom,-51.7963,-59.5236,2020-07-27,13,0,13,0,Europe
49060,Saint Pierre and Miquelon,France,46.8852,-56.3159,2020-07-27,4,0,1,3,Europe
49066,NaN,Tajikistan,38.8610,71.2761,2020-07-27,7235,60,6028,1147,Europe

The previous example **groups specific rows**, but does not perform any operation on them. When operations are performed in addition to the grouping, we talk of **aggregation**. Below is an example of aggregation: we sum the amount of confirmed COVID cases per each WHO region.

In [44]:
confirmed_cases_df = df.groupby('WHO Region')['Confirmed'].sum()
confirmed_cases_df

WHO Region
Africa                    21791827
Americas                 402261194
Eastern Mediterranean     74082892
Europe                   248879793
South-East Asia           55118365
Western Pacific           26374411
Name: Confirmed, dtype: int64

We will now compute the average of confirmed cases and death cases per WHO region:

In [39]:
df.groupby('WHO Region')[['Deaths', 'Confirmed']].mean()

                            Deaths     Confirmed
WHO Region
Africa                   48.756427   2414.874446
Americas               2238.586031  46514.939177
Eastern Mediterranean   465.190764  17911.724371
Europe                 1281.319149  16547.858577
South-East Asia         775.603191  29318.279255
Western Pacific          90.176983   2550.716731

The two operations (`sum` and `mean`) can be performed together, with the help of `agg()`. Try doing it yourself.
> Hint: agg() takes as parameter a dictionary where the keys are the column names, and the values are the operations you want to perform, such as 'sum' or 'mean'.

In [ ]:
# Exercise: Group the dataset by WHO Region and display the sum of confirmed cases, and the mean of deaths.

In [ ]:
# Solution: Aggregation

df.groupby('WHO Region').agg({
    'Confirmed': 'sum',    # sum Quantity per category
    'Deaths': 'mean'       # average Price per category
})

                       Confirmed       Deaths
WHO Region
Africa                  21791827    48.756427
Americas               402261194  2238.586031
Eastern Mediterranean   74082892   465.190764
Europe                 248879793  1281.319149
South-East Asia         55118365   775.603191
Western Pacific         26374411    90.176983

##### Merging dataframes

The most widely used technique is the **inner merge**, that merges dataframes by keeping only rows present in both dataframes, and including all columns. Information about other kinds of merging can be found [here](https://pandas.pydata.org/docs/reference/api/pandas.merge.html).

In [40]:
second_df = pd.DataFrame({
        'Population (estimate)': [
        1585000000,   # Africa
        1062000000,   # Americas
        745000000,    # Eastern Mediterranean
        743000000,    # Europe
        695000000,    # South-East Asia
        2200000000    # Western Pacific
    ],
    'WHO Region': ['Africa','Americas','Eastern Mediterranean','Europe', 'South-East Asia', 'Western Pacific']
})

In [52]:
merged_inner = pd.merge(confirmed_cases_df, second_df, on='WHO Region', how='inner')
merged_inner
merged_inner.shape

(6, 3)

In [ ]:
# Exercise: Have a look at the above link, and take a guess at what a left merge would output. 
# After that, perform the left merge and see if the answer corresponds to your guess.